// Export pages
export '/pages/home_page/home_page_widget.dart' show HomePageWidget;
export '/pages/account_page/account_page_widget.dart' show AccountPageWidget;
export '/pages/transactions/transaction_history_page/transaction_history_page_widget.dart'
    show TransactionHistoryPageWidget;
export '/pages/debug_action_page/debug_action_page_widget.dart'
    show DebugActionPageWidget;
export '/pages/statistic_page/statistic_page_widget.dart'
    show StatisticPageWidget;
export '/pages/goal_and_budget_page/goal_and_budget_page_widget.dart'
    show GoalAndBudgetPageWidget;
export '/pages/goals/add_goal_page/add_goal_page_widget.dart'
    show AddGoalPageWidget;
export '/pages/goals/add_goal_confirm_page/add_goal_confirm_page_widget.dart'
    show AddGoalConfirmPageWidget;
export '/pages/goals/add_goal_income_page/add_goal_income_page_widget.dart'
    show AddGoalIncomePageWidget;
export '/pages/goals/goal_details_page/goal_details_page_widget.dart'
    show GoalDetailsPageWidget;
export '/pages/goals/edit_goal_page/edit_goal_page_widget.dart'
    show EditGoalPageWidget;
export '/pages/goals/edit_goal_income_page/edit_goal_income_page_widget.dart'
    show EditGoalIncomePageWidget;
export '/pages/goals/edit_goal_confirm_page/edit_goal_confirm_page_widget.dart'
    show EditGoalConfirmPageWidget;
export '/pages/goals/goal_saving_data_table_page/goal_saving_data_table_page_widget.dart'
    show GoalSavingDataTablePageWidget;
export '/pages/budgets/add_budget_page/add_budget_page_widget.dart'
    show AddBudgetPageWidget;
export '/pages/budgets/add_budget_allocate_page/add_budget_allocate_page_widget.dart'
    show AddBudgetAllocatePageWidget;
export '/pages/budgets/add_budget_confirm_page/add_budget_confirm_page_widget.dart'
    show AddBudgetConfirmPageWidget;
export '/pages/budgets/budget_details_page/budget_details_page_widget.dart'
    show BudgetDetailsPageWidget;
export '/pages/budgets/edit_budget_page/edit_budget_page_widget.dart'
    show EditBudgetPageWidget;
export '/pages/budgets/edit_budget_allocate_page/edit_budget_allocate_page_widget.dart'
    show EditBudgetAllocatePageWidget;
export '/pages/budgets/edit_budget_confirm_page/edit_budget_confirm_page_widget.dart'
    show EditBudgetConfirmPageWidget;
export '/pages/wealth/add_wealth_info_page/add_wealth_info_page_widget.dart'
    show AddWealthInfoPageWidget;
export '/pages/wealth/wealth_info_page/wealth_info_page_widget.dart'
    show WealthInfoPageWidget;
export '/pages/wealth/edit_wealth_info_page/edit_wealth_info_page_widget.dart'
    show EditWealthInfoPageWidget;
export '/pages/wealth/edit_wealth_additional_info_page/edit_wealth_additional_info_page_widget.dart'
    show EditWealthAdditionalInfoPageWidget;
export '/pages/retirement/retirement_personal_form_page/retirement_personal_form_page_widget.dart'
    show RetirementPersonalFormPageWidget;
export '/pages/retirement/retirement_financial_form_page/retirement_financial_form_page_widget.dart'
    show RetirementFinancialFormPageWidget;
export '/pages/retirement/retirement_savings_form_page/retirement_savings_form_page_widget.dart'
    show RetirementSavingsFormPageWidget;
export '/pages/retirement/retirement_result_page/retirement_result_page_widget.dart'
    show RetirementResultPageWidget;
export '/pages/other_menu_page/other_menu_page_widget.dart'
    show OtherMenuPageWidget;
export '/pages/taxs/taxs_plan_management_page/taxs_plan_management_page_widget.dart'
    show TaxsPlanManagementPageWidget;
export '/pages/taxs/taxes_personal_info_form_page/taxes_personal_info_form_page_widget.dart'
    show TaxesPersonalInfoFormPageWidget;
export '/pages/taxs/add_taxes_page/add_taxes_page_widget.dart'
    show AddTaxesPageWidget;
export '/pages/taxs/taxes_plan_details_page/taxes_plan_details_page_widget.dart'
    show TaxesPlanDetailsPageWidget;
export '/pages/taxs/edit_taxes_page/edit_taxes_page_widget.dart'
    show EditTaxesPageWidget;
export '/pages/taxs/edit_taxes_income_page/edit_taxes_income_page_widget.dart'
    show EditTaxesIncomePageWidget;
export '/pages/taxs/taxes_deduction_detail_page/taxes_deduction_detail_page_widget.dart'
    show TaxesDeductionDetailPageWidget;
export '/pages/taxs/taxes_donate_deduct_form_page/taxes_donate_deduct_form_page_widget.dart'
    show TaxesDonateDeductFormPageWidget;
export '/pages/taxs/taxes_insurance_investment_deduct_form_page/taxes_insurance_investment_deduct_form_page_widget.dart'
    show TaxesInsuranceInvestmentDeductFormPageWidget;
export '/pages/fv_calculator/f_v_calculator_form_page/f_v_calculator_form_page_widget.dart'
    show FVCalculatorFormPageWidget;
export '/pages/fv_calculator/f_v_calculator_result_page/f_v_calculator_result_page_widget.dart'
    show FVCalculatorResultPageWidget;
export '/pages/transactions/add_trans_page/add_trans_page_widget.dart'
    show AddTransPageWidget;
export '/pages/transactions/edit_trans_page/edit_trans_page_widget.dart'
    show EditTransPageWidget;
export '/pages/transactions/add_trans_transfer_page/add_trans_transfer_page_widget.dart'
    show AddTransTransferPageWidget;
export '/pages/transactions/edit_trans_transfer_page/edit_trans_transfer_page_widget.dart'
    show EditTransTransferPageWidget;
export '/pages/setting_page/setting_page_widget.dart' show SettingPageWidget;
export '/pages/export_select_page/export_select_page_widget.dart'
    show ExportSelectPageWidget;
